# Generated by Django 3.0 on 2019-12-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_note_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
