# Generated by Django 3.0 on 2019-12-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_note_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='draft',
            field=models.BooleanField(default=False),
        ),
    ]
