# Generated by Django 3.0 on 2019-12-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_auto_20191210_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftnote',
            name='checkboxes',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='draftnote',
            name='message',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='draftnote',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
