# Generated by Django 3.0 on 2019-12-25 21:39

from django.db import migrations


def update_notes(apps, schema_editor):
    Note = apps.get_model('notes', 'Note')
    Note.objects.all().update(status='published')


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_auto_20191225_2119'),
    ]

    operations = [
        migrations.RunPython(update_notes)
    ]
