# Generated by Django 3.0 on 2020-01-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macros', '0002_auto_20200127_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='macro',
            name='tags',
        ),
        migrations.AddField(
            model_name='macro',
            name='tag',
            field=models.ManyToManyField(blank=True, to='macros.Tag'),
        ),
    ]
