# Generated by Django 3.0 on 2020-01-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macros', '0003_auto_20200127_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macro',
            name='abbreviation',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
