# Generated by Django 3.0 on 2020-01-27 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('macros', '0004_auto_20200127_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='macro',
            old_name='tag',
            new_name='tags',
        ),
    ]
