# Generated by Django 3.0 on 2020-01-31 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macros', '0005_auto_20200127_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macro',
            name='content',
            field=models.TextField(blank=True, max_length=100000, null=True),
        ),
    ]
