# Generated by Django 3.0 on 2020-01-31 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('macros', '0006_auto_20200131_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macro',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='macros.Type'),
        ),
    ]
