# Generated by Django 3.0 on 2020-02-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macros', '0007_auto_20200131_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='MacroNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='macro',
            name='content',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('title',)},
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('title',)},
        ),
        migrations.AlterUniqueTogether(
            name='type',
            unique_together={('title',)},
        ),
    ]
