# Generated by Django 3.0 on 2020-02-04 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('macros', '0008_auto_20200204_0857'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MacroNote',
            new_name='Note',
        ),
    ]
