# Generated by Django 3.0 on 2020-02-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macros', '0009_auto_20200204_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.TextField(max_length=100000),
        ),
    ]
