# Generated by Django 3.0 on 2020-02-04 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('macros', '0010_auto_20200204_1023'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
