# Generated by Django 3.0 on 2020-02-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macros', '0011_delete_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100000)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
