# Generated by Django 3.0 on 2020-02-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macros', '0012_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macro',
            name='content',
            field=models.TextField(max_length=10000),
        ),
    ]
