# Generated by Django 3.0 on 2020-02-05 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('macros', '0013_auto_20200205_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='macro',
            old_name='abbreviation',
            new_name='Abbreviation',
        ),
        migrations.RenameField(
            model_name='macro',
            old_name='category',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='macro',
            old_name='content',
            new_name='Content',
        ),
        migrations.RenameField(
            model_name='macro',
            old_name='tags',
            new_name='Tags',
        ),
        migrations.RenameField(
            model_name='macro',
            old_name='title',
            new_name='Title',
        ),
        migrations.RenameField(
            model_name='macro',
            old_name='type',
            new_name='Type',
        ),
    ]
